language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.1.0

script: 
  - ./gradlew unitTest
  - ./gradlew assembleRelease

deploy:
  provider: releases
  api-key: "1daa428fb4d9271a1c2a957f42265f84ae1cfaad"
  file:
    - "app/build/outputs/apk/app-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
