language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.1.0

before_script:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && $TRAVIS_TAG=\"SNAPSHOT\""

script: 
  ./gradlew assembleRelease

deploy:
  provider: releases
  api-key: "1daa428fb4d9271a1c2a957f42265f84ae1cfaad"
  file:
    - "app/build/apk/app-release.apk"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
