python blur_image.py ../app/src/main/assets/Images/wineries/13th-street-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/angels-gate-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/between-the-lines-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/calamus-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/cattail-creek-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/cave-spring-cellars-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/colaneri-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/coyotes-run-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/creekside-estate-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/de-sousa-wine-cellars-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/di-profio-wines-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/diamond-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/featherstone-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/fielding-estate-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/flat-rock-cellars-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/frogpond-farm-organic-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/good-earth-food-and-wine-co-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/henry-of-pelham-family-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/hernder-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/inniskillin-wines-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/jackson-triggs-niagara-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/konzelmann-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/lailey-vineyard-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/legends-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/malivoire-wine-company-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/marynissen-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/megalomaniac-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/palatine-hills-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/peller-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/peninsula-ridge-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/pillitteri-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/pondview-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/ravine-vineyard-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/reif-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/riverview-cellars-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/silversmith-brewing-company-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/small-talk-vineyards-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/southbrook-vineyards-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/strewn-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/sue-ann-staff-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/sunnybrook-farm-estate-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/the-foreign-affair-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/the-ice-house-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/thirty-bench-wine-makers-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/trius-winery-at-hillebrand-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/vieni-estates-inc-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/vignoble-winery-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/vineland-estates-full.jpg
python blur_image.py ../app/src/main/assets/Images/wineries/w-placeholder-full.jpg
